# Generated by Django 5.0.2 on 2024-03-15 02:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality_name', models.CharField(default='Physician', max_length=255)),
                ('related_terms', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='HospitalUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(max_length=255)),
                ('role_group', models.CharField(default='visitor', max_length=255)),
                ('online', models.BooleanField(default=False)),
                ('channel_name', models.CharField(default='', max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.CharField(default='consultant', max_length=255)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
                ('assigned_patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chatapp.hospitalusers')),
            ],
        ),
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('chat_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chat_data', models.JSONField(default={'chat_data': [], 'chat_time': 1710470403})),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_receiver', to='chatapp.hospitalusers')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_sender', to='chatapp.hospitalusers')),
            ],
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('appointment_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appointment_date', models.DateField(null=True)),
                ('appointment_time', models.TimeField(null=True)),
                ('appointment_initial_date', models.DateField(null=True)),
                ('appointment_initial_time', models.TimeField(null=True)),
                ('appointment_setter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_setter', to='chatapp.hospitalusers')),
                ('appointment_with', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_with', to='chatapp.hospitalusers')),
            ],
        ),
        migrations.CreateModel(
            name='PatientRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_title', models.CharField(default='', max_length=255)),
                ('record_details', models.CharField(default='', max_length=255)),
                ('record_date', models.DateField(null=True)),
                ('record_time', models.TimeField(null=True)),
                ('record_timestamp', models.PositiveBigIntegerField(default=0)),
                ('record_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record_by_user', to='chatapp.hospitalusers')),
                ('record_for', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record_for_user', to='chatapp.hospitalusers')),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chatapp.doctors')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_details', models.CharField(default='', max_length=255)),
                ('assigned_test_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatapp.doctors')),
                ('assigned_test_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatapp.patients')),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy_name', models.CharField(default='', max_length=255)),
                ('pharmacy_personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatapp.hospitalusers')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDrugs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('delivery_man', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chatapp.hospitalusers')),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chatapp.patients')),
                ('assigned_pharmacy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chatapp.pharmacies')),
            ],
        ),
        migrations.CreateModel(
            name='Prescriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescribed_medicine', models.CharField(default='', max_length=255)),
                ('prescribed_dose', models.CharField(default='', max_length=255)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chatapp.orderdrugs')),
                ('prescribed_to_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatapp.patients')),
                ('prescribing_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatapp.doctors')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(default='', max_length=255)),
                ('item_available_amount', models.IntegerField(default=0)),
                ('item_sold_amount', models.IntegerField(default=0)),
                ('item_unit_price', models.IntegerField(default=0)),
                ('item_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatapp.pharmacies')),
            ],
        ),
        migrations.AddField(
            model_name='orderdrugs',
            name='item_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chatapp.productcatalog'),
        ),
    ]
