# Generated by Django 5.0.2 on 2024-03-15 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='chat_data',
            field=models.JSONField(default={'chat_data': [], 'chat_time': 1710470424}),
        ),
    ]
