# Generated by Django 5.0.2 on 2024-03-15 02:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_alter_chats_chat_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecords',
            name='record_uuid',
            field=models.UUIDField(default=uuid.UUID('ef37cb3c-2d58-4bac-aa4d-e3e5f148d1f1'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='chats',
            name='chat_data',
            field=models.JSONField(default={'chat_data': [], 'chat_time': 1710470632}),
        ),
        migrations.AlterField(
            model_name='chats',
            name='chat_uuid',
            field=models.UUIDField(default=uuid.UUID('79bee0d9-6cf1-4390-af6a-3123748323af'), editable=False, primary_key=True, serialize=False),
        ),
    ]
