# Generated by Django 5.0.2 on 2024-03-15 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0004_alter_chats_chat_data_alter_chats_chat_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='appointment_details',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='chats',
            name='chat_data',
            field=models.JSONField(default={'chat_data': [], 'chat_time': 1710472857}),
        ),
    ]
