# Generated by Django 5.0.2 on 2024-03-16 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0006_orderdrugs_order_uuid_orderdrugs_ordered_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='chat_data',
            field=models.JSONField(default={'chat_data': [], 'chat_time': 1710557946}),
        ),
    ]
