# Generated by Django 5.0.2 on 2024-03-16 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0008_rename_orderdrugs_orders_remove_prescriptions_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='chat_data',
            field=models.JSONField(default={'chat_data': [], 'chat_time': 1710558924}),
        ),
        migrations.AlterField(
            model_name='productcatalog',
            name='item_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatapp.hospitalusers'),
        ),
    ]
