# Generated by Django 5.0.2 on 2024-03-16 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0011_alter_chats_chat_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptions',
            name='notes',
            field=models.CharField(default='Medicine', max_length=255),
        ),
        migrations.AlterField(
            model_name='chats',
            name='chat_data',
            field=models.JSONField(default={'chat_data': [], 'chat_time': 1710559882}),
        ),
    ]
