# Generated by Django 5.0.2 on 2024-03-16 03:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0015_alter_chats_chat_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptions',
            name='prescription_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 16, 6, 43, 2, 990232)),
        ),
        migrations.AlterField(
            model_name='chats',
            name='chat_data',
            field=models.JSONField(default={'chat_data': [], 'chat_time': 1710560582}),
        ),
    ]
