# Generated by Django 5.0.2 on 2024-03-16 04:14

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0016_prescriptions_prescription_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='chat_data',
            field=models.JSONField(default={'chat_data': [], 'chat_time': 1710562484}),
        ),
        migrations.AlterField(
            model_name='prescriptions',
            name='prescribed_to_patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescribing_patient', to='chatapp.hospitalusers'),
        ),
        migrations.AlterField(
            model_name='prescriptions',
            name='prescribing_doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescribing_doctor', to='chatapp.hospitalusers'),
        ),
        migrations.AlterField(
            model_name='prescriptions',
            name='prescription_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 16, 7, 14, 44, 68245)),
        ),
    ]
