# Generated by Django 5.0.2 on 2024-08-24 03:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0017_alter_chats_chat_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='chat_data',
            field=models.JSONField(default={'chat_data': [], 'chat_time': 1724469330}),
        ),
        migrations.AlterField(
            model_name='prescriptions',
            name='prescription_date',
            field=models.DateField(default=datetime.datetime(2024, 8, 24, 6, 15, 30, 515810)),
        ),
    ]
