# Generated by Django 5.1 on 2024-08-26 03:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0018_alter_chats_chat_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='chat_data',
            field=models.JSONField(default={'chat_data': [], 'chat_time': 1724643495}),
        ),
        migrations.AlterField(
            model_name='prescriptions',
            name='prescription_date',
            field=models.DateField(default=datetime.datetime(2024, 8, 26, 3, 38, 14, 984197)),
        ),
    ]
